/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package OpeningHours

import OpeningHours.domain.manager.WorkingHoursConverter
import OpeningHours.domain.model.getDisplayString

fun main(args: Array<String>) {
    val arguments = getArguments(args)
    val inputFile = getInputFile(arguments.inputFilePath)
    val extRestaurantData = parseData(inputFile)
    val restaurantData = WorkingHoursConverter.getRestaurantDataNew(extRestaurantData)
    val result = restaurantData.getDisplayString()

    if (arguments.outputFilePath == null) {
        println(result)
    } else {
        writeOutput(arguments.outputFilePath, result)
    }
}